/**
 * HIGH ERA AGENCY - Research Output Templates
 *
 * Markdown templates for competitive intelligence deliverables.
 */

import type {
  CompetitiveIntelligence,
  CompanyProfile,
  OpportunityGap,
  CompetitiveThreat,
  ResearchResult,
} from "./analyst";

/**
 * Generate full competitive research report
 */
export function generateResearchReport(result: ResearchResult): string {
  const { data, insights, recommendations } = result;

  return `# Competitive Intelligence Report
## ${data.target.name}

**Generated:** ${new Date(result.completedAt).toLocaleDateString()}
**Research ID:** ${result.id}

---

## Executive Summary

${insights.map((i) => `- ${i}`).join("\n")}

---

## Target Company Profile

${generateCompanySection(data.target)}

---

## Competitive Landscape

**Total Competitors Analyzed:** ${data.competitors.length}
${data.landscape.marketLeader ? `**Market Leader:** ${data.landscape.marketLeader}` : ""}

### Competitors

${data.competitors.map((c) => generateCompanySection(c)).join("\n---\n\n")}

---

## Opportunity Gaps

${generateGapsSection(data.gaps)}

---

## Competitive Threats

${generateThreatsSection(data.threats)}

---

## Recommendations

${recommendations.map((r, i) => `${i + 1}. ${r}`).join("\n\n")}

---

## Appendix: Raw Data

<details>
<summary>Full Research Data (JSON)</summary>

\`\`\`json
${JSON.stringify(data, null, 2)}
\`\`\`

</details>

---

*Report generated by High Era Agency Competitive Analyst*
`;
}

/**
 * Generate company profile section
 */
function generateCompanySection(company: CompanyProfile): string {
  let section = `### ${company.name}
**Domain:** ${company.domain}
${company.tagline ? `**Tagline:** ${company.tagline}` : ""}
${company.positioning ? `**Positioning:** ${company.positioning}` : ""}
`;

  if (company.seo) {
    section += `
#### SEO Profile
| Metric | Value |
|--------|-------|
${company.seo.domainAuthority ? `| Domain Authority | ${company.seo.domainAuthority} |` : ""}
${company.seo.organicKeywords ? `| Organic Keywords | ${company.seo.organicKeywords.toLocaleString()} |` : ""}
${company.seo.organicTraffic ? `| Est. Organic Traffic | ${company.seo.organicTraffic.toLocaleString()}/mo |` : ""}
${company.seo.backlinks ? `| Backlinks | ${company.seo.backlinks.toLocaleString()} |` : ""}
${company.seo.referringDomains ? `| Referring Domains | ${company.seo.referringDomains.toLocaleString()} |` : ""}
`;

    if (company.seo.topKeywords?.length) {
      section += `
**Top Keywords:**
| Keyword | Position | Volume |
|---------|----------|--------|
${company.seo.topKeywords
  .slice(0, 10)
  .map((k) => `| ${k.keyword} | ${k.position} | ${k.volume.toLocaleString()} |`)
  .join("\n")}
`;
    }
  }

  if (company.pricing) {
    section += `
#### Pricing
**Model:** ${company.pricing.model}
${company.pricing.freeTrialDays ? `**Free Trial:** ${company.pricing.freeTrialDays} days` : ""}
${company.pricing.lowestPrice ? `**Starting at:** $${company.pricing.lowestPrice}/mo` : ""}
`;

    if (company.pricing.tiers?.length) {
      section += `
| Tier | Price | Billing |
|------|-------|---------|
${company.pricing.tiers.map((t) => `| ${t.name} | $${t.price} | ${t.billing} |`).join("\n")}
`;
    }
  }

  if (company.technology) {
    section += `
#### Technology Stack
${company.technology.stack?.length ? `**Core:** ${company.technology.stack.join(", ")}` : ""}
${company.technology.analytics?.length ? `**Analytics:** ${company.technology.analytics.join(", ")}` : ""}
${company.technology.marketing?.length ? `**Marketing:** ${company.technology.marketing.join(", ")}` : ""}
`;
  }

  if (company.content) {
    section += `
#### Content
${company.content.blogPosts ? `**Blog Posts:** ~${company.content.blogPosts}` : ""}
${company.content.contentTypes?.length ? `**Content Types:** ${company.content.contentTypes.join(", ")}` : ""}
`;
  }

  if (company.social) {
    section += `
#### Social Presence
${company.social.twitter ? `**Twitter:** @${company.social.twitter.handle} (${company.social.twitter.followers.toLocaleString()} followers)` : ""}
${company.social.linkedin ? `**LinkedIn:** ${company.social.linkedin.followers?.toLocaleString() || "N/A"} followers` : ""}
${company.social.totalFollowers ? `**Total Reach:** ${company.social.totalFollowers.toLocaleString()}` : ""}
`;
  }

  return section;
}

/**
 * Generate gaps section
 */
function generateGapsSection(gaps: OpportunityGap[]): string {
  if (!gaps.length) {
    return "*No significant gaps identified*";
  }

  const byImpact = {
    high: gaps.filter((g) => g.potentialImpact === "high"),
    medium: gaps.filter((g) => g.potentialImpact === "medium"),
    low: gaps.filter((g) => g.potentialImpact === "low"),
  };

  let section = "";

  if (byImpact.high.length) {
    section += `### High Impact Opportunities

${byImpact.high
  .map(
    (g) => `#### ${g.type.charAt(0).toUpperCase() + g.type.slice(1)} Gap
${g.description}

- **Competitors doing this:** ${g.competitors.join(", ")}
- **Effort:** ${g.effort}
`
  )
  .join("\n")}
`;
  }

  if (byImpact.medium.length) {
    section += `### Medium Impact Opportunities

${byImpact.medium.map((g) => `- **${g.type}:** ${g.description}`).join("\n")}
`;
  }

  if (byImpact.low.length) {
    section += `### Lower Priority

${byImpact.low.map((g) => `- ${g.description}`).join("\n")}
`;
  }

  return section;
}

/**
 * Generate threats section
 */
function generateThreatsSection(threats: CompetitiveThreat[]): string {
  if (!threats.length) {
    return "*No significant threats identified*";
  }

  const bySeverity = {
    high: threats.filter((t) => t.severity === "high"),
    medium: threats.filter((t) => t.severity === "medium"),
    low: threats.filter((t) => t.severity === "low"),
  };

  let section = "";

  if (bySeverity.high.length) {
    section += `### ⚠️ High Severity

${bySeverity.high
  .map(
    (t) => `- **${t.competitor}:** ${t.threat}
  - Timeframe: ${t.timeframe}`
  )
  .join("\n\n")}
`;
  }

  if (bySeverity.medium.length) {
    section += `### Medium Severity

${bySeverity.medium.map((t) => `- **${t.competitor}:** ${t.threat}`).join("\n")}
`;
  }

  if (bySeverity.low.length) {
    section += `### Monitor

${bySeverity.low.map((t) => `- ${t.competitor}: ${t.threat}`).join("\n")}
`;
  }

  return section;
}

/**
 * Generate quick scan summary (1-pager)
 */
export function generateQuickScan(company: CompanyProfile): string {
  return `# Quick Scan: ${company.name}

**Domain:** ${company.domain}
**Scanned:** ${new Date().toLocaleDateString()}

---

## At a Glance

${company.tagline || "*No tagline detected*"}

## Key Metrics

| Category | Status |
|----------|--------|
| SEO | ${company.seo?.domainAuthority ? `DA ${company.seo.domainAuthority}` : "Unknown"} |
| Pricing | ${company.pricing?.model || "Unknown"} ${company.pricing?.lowestPrice ? `from $${company.pricing.lowestPrice}` : ""} |
| Content | ${company.content?.blogPosts ? `~${company.content.blogPosts} posts` : "Unknown"} |
| Tech | ${company.technology?.stack?.slice(0, 3).join(", ") || "Unknown"} |

## Technology Detected

${company.technology?.stack?.length ? company.technology.stack.map((t) => `- ${t}`).join("\n") : "- No technologies detected"}

${company.technology?.analytics?.length ? `\n**Analytics:** ${company.technology.analytics.join(", ")}` : ""}
${company.technology?.marketing?.length ? `\n**Marketing Tools:** ${company.technology.marketing.join(", ")}` : ""}

---

*Quick scan by High Era Agency*
`;
}

/**
 * Generate competitor comparison matrix
 */
export function generateComparisonMatrix(
  target: CompanyProfile,
  competitors: CompanyProfile[]
): string {
  const all = [target, ...competitors];

  return `# Competitive Comparison Matrix

**Target:** ${target.name}
**Competitors:** ${competitors.map((c) => c.name).join(", ")}

---

## SEO Comparison

| Company | Domain Authority | Organic Keywords | Est. Traffic |
|---------|------------------|------------------|--------------|
${all
  .map(
    (c) =>
      `| ${c.name} | ${c.seo?.domainAuthority || "-"} | ${c.seo?.organicKeywords?.toLocaleString() || "-"} | ${c.seo?.organicTraffic?.toLocaleString() || "-"} |`
  )
  .join("\n")}

## Pricing Comparison

| Company | Model | Entry Price | Free Trial |
|---------|-------|-------------|------------|
${all
  .map(
    (c) =>
      `| ${c.name} | ${c.pricing?.model || "-"} | ${c.pricing?.lowestPrice ? "$" + c.pricing.lowestPrice : "-"} | ${c.pricing?.freeTrialDays ? c.pricing.freeTrialDays + " days" : "-"} |`
  )
  .join("\n")}

## Content Comparison

| Company | Blog Posts | Content Types |
|---------|------------|---------------|
${all
  .map(
    (c) =>
      `| ${c.name} | ${c.content?.blogPosts || "-"} | ${c.content?.contentTypes?.join(", ") || "-"} |`
  )
  .join("\n")}

## Technology Comparison

| Company | Stack | Analytics | Marketing |
|---------|-------|-----------|-----------|
${all
  .map(
    (c) =>
      `| ${c.name} | ${c.technology?.stack?.slice(0, 2).join(", ") || "-"} | ${c.technology?.analytics?.slice(0, 2).join(", ") || "-"} | ${c.technology?.marketing?.slice(0, 2).join(", ") || "-"} |`
  )
  .join("\n")}

---

*Comparison matrix by High Era Agency*
`;
}

/**
 * Generate SEO gap analysis report
 */
export function generateSEOGapReport(
  target: CompanyProfile,
  competitors: CompanyProfile[],
  keywordGaps: Array<{
    keyword: string;
    competitorRank: number;
    targetRank: number | null;
    volume: number;
    competitor: string;
  }>
): string {
  return `# SEO Gap Analysis
## ${target.name} vs Competitors

---

## Summary

**Your Domain Authority:** ${target.seo?.domainAuthority || "Unknown"}
**Avg Competitor DA:** ${Math.round(
    competitors.reduce((sum, c) => sum + (c.seo?.domainAuthority || 0), 0) /
      competitors.length
  ) || "Unknown"}

**Your Organic Keywords:** ${target.seo?.organicKeywords?.toLocaleString() || "Unknown"}
**Avg Competitor Keywords:** ${Math.round(
    competitors.reduce((sum, c) => sum + (c.seo?.organicKeywords || 0), 0) /
      competitors.length
  ).toLocaleString() || "Unknown"}

---

## Keyword Gaps

Keywords where competitors rank but you don't:

| Keyword | Volume | Competitor | Their Rank | Your Rank |
|---------|--------|------------|------------|-----------|
${keywordGaps
  .slice(0, 20)
  .map(
    (g) =>
      `| ${g.keyword} | ${g.volume.toLocaleString()} | ${g.competitor} | ${g.competitorRank} | ${g.targetRank || "Not ranking"} |`
  )
  .join("\n")}

---

## Authority Gap

| Competitor | Their DA | Gap |
|------------|----------|-----|
${competitors
  .map(
    (c) =>
      `| ${c.name} | ${c.seo?.domainAuthority || "-"} | ${c.seo?.domainAuthority && target.seo?.domainAuthority ? (c.seo.domainAuthority > target.seo.domainAuthority ? "+" : "") + (c.seo.domainAuthority - target.seo.domainAuthority) : "-"} |`
  )
  .join("\n")}

---

## Recommendations

1. **Quick Wins:** Target keywords where competitors rank #11-20 (page 2)
2. **Authority Building:** Focus on content that attracts backlinks
3. **Content Gaps:** Create content for topics competitors cover that you don't

---

*SEO Gap Analysis by High Era Agency*
`;
}
